version: '3.4'

services:
    loki:
        image: "grafana/loki:latest"
        container_name: ${APP_PREFIX}-loki
        hostname: logs
        volumes:
            - ./loki/config:/mnt/config
            - ./loki-data:/loki
        ports:
            # - "3100:3100" # http and Grafana data source
            - "${LOKI_GRPC_PORT}:9095" # grpc
        healthcheck:
            test: ["CMD-SHELL", "wget -O /dev/null http://localhost:3100/ready || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
    grafana:
        image: grafana/grafana-oss:latest-ubuntu
        container_name: ${APP_PREFIX}-grafana
        hostname: grafana
        user: "1000"
        restart: "unless-stopped"
        ports: 
            - "${GRAFANA_EXTERNAL_PORT}:3000"
        healthcheck:
            test: ["CMD-SHELL", "curl -f localhost:3000/api/health || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - ./grafana-data:/var/lib/grafana
        #     - ./config/grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        depends_on:
            - loki