receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  # resource:
    # attributes:
      # - action: insert
        # key: service_name
        # from_attribute: service.name
      # - action: insert
        # key: loki.resource.labels
        # value: service_name

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: SystemName

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ loki ]
